//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trabajo_final_POO.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Reservacion_Hab = new HashSet<Reservacion_Hab>();
        }
    
        public int Id { get; set; }
        public string Codigo_Clie { get; set; }
        public string Nombre_clie { get; set; }
        public string Ape1_clie { get; set; }
        public string Ape2_clie { get; set; }
        public string Numero_identificacion { get; set; }
        public int Tipo_ClienteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservacion_Hab> Reservacion_Hab { get; set; }
        public virtual Tipo_Cliente Tipo_Cliente { get; set; }
    }
}
